# projects/topic_data.py
# Department-specific project topics for the Topic Generator

DEPARTMENT_TOPICS = {
    # FACULTY OF AGRICULTURE
    "Agricultural Economics and Extension": [
        "Economic analysis of sesame seed marketing chain in Nasarawa State",
        "Impact of Fadama III project on income of rice farmers in Lafia",
        "Adoption rate of improved cassava varieties among smallholder farmers in Kokona LGA",
        "Profitability and constraints of small-scale poultry egg production in Keffi",
        "Effects of herder-farmer conflicts on agricultural productivity in Obi LGA",
        "Willingness to pay for agricultural insurance by crop farmers in Nasarawa State",
        "Role of social media in agricultural information dissemination among youth farmers",
        "Gender analysis of access to agricultural credits in Doma LGA",
        "Value chain analysis of yam production and its post-harvest losses",
        "Impact of climate change perception on farming practices in the Southern Zone",
    ],
    "Agronomy": [
        "Response of local maize variety to different organic fertilizers (poultry manure, compost)",
        "Evaluation of soybean genotypes for drought tolerance in the Keffi environment",
        "Effect of planting dates on the growth and yield of sweet potato",
        "Weed management strategies in upland rice cultivation",
        "Seed viability and germination tests for indigenous vegetable seeds",
        "Intercropping compatibility of cassava and groundnut",
        "Soil amendment using biochar from rice husks for tomato production",
        "Assessment of soil fertility status in selected farmlands in Nasarawa West",
        "Control of Striga (witchweed) in sorghum fields using cultural methods",
        "Growth performance of Moringa oleifera under different pruning regimes",
    ],
    "Animal Science": [
        "Carcass characteristics of broiler chickens fed diets containing Moringa oleifera leaf meal",
        "Effects of replacing maize with fermented cassava peels in rabbit diets",
        "Assessment of ethno-veterinary practices among Fulani herdsmen in Nasarawa State",
        "Semen quality analysis of local turkey cocks supplemented with selenium",
        "Prevalence of gastrointestinal parasites in locally reared goats in Keffi",
        "Milk production and composition of White Fulani cows under semi-intensive system",
        "Haematological parameters of broilers fed neem leaf extract as an antibiotic alternative",
        "Feed intake and growth performance of pigs fed watermelon rind meal",
        "Characterization of local chicken ecotypes in Nasarawa State",
        "Effects of housing density on stress indicators in layers",
    ],
    "Forestry, Wildlife and Ecotourism": [
        "Growth performance of Clarias gariepinus (catfish) fed household food waste diet",
        "Water quality assessment of selected fish ponds in Lafia",
        "Economic analysis of artisanal fishing in the River Benue (Nasarawa segment)",
        "Prevalence of fish parasites in Lake Nasarawa",
        "Effect of stocking density on survival rate of Nile tilapia in concrete tanks",
        "Proximate composition of smoked fish using different local smoking kilns",
        "Potential of duckweed (Lemna minor) as feed for tilapia fingerlings",
        "Assessment of fish farming adoption among youth in Doma",
        "Reproductive performance of African catfish induced with different hormones",
        "Design and construction of a low-cost water recirculation system for aquaponics",
    ],
    "Home Science and Management": [
        "Mapping of soil erosion prone areas in Nasarawa State using GIS",
        "Effects of different mulch types on soil moisture conservation and maize yield",
        "Physico-chemical properties of soils around solid mineral mining sites in Nasarawa",
        "Carbon sequestration potential of soils under different land use systems",
        "Assessment of heavy metal contamination in vegetables grown along major highways",
        "Soil suitability evaluation for citrus production in the Northern Zone",
        "Effect of long-term fertilizer application on soil pH and microbial activity",
        "Use of sawdust ash as a liming material for acid soils",
        "Assessment of irrigation water quality from shallow wells in agrarian communities",
        "Land capability classification for selected areas in Keffi",
    ],
    
    # FACULTY OF NATURAL AND APPLIED SCIENCES
    "Computer Science": [
        "Design and implementation of a web-based farm produce marketplace for Nasarawa State",
        "Development of a mobile app for reporting and tracking farmer-herder conflicts (GIS-based)",
        "NASU E-Campus: An enhanced student portal with integrated lecture notes and forum features",
        "Predictive model for student academic performance using machine learning",
        "Automated system for detecting fake news in Nigerian social media spaces",
        "Design of a biometric-based attendance management system for university staff",
        "Sentiment analysis of public opinion on government policies from Twitter data",
        "Development of an offline-capable educational app for secondary school STEM subjects",
        "Network intrusion detection system using deep learning techniques",
        "Design of a virtual reality (VR) tour of Nasarawa State University",
    ],
    "Microbiology": [
        "Antimicrobial activity of extracts from local plants against wound pathogens",
        "Mycoflora and aflatoxin contamination of stored grains in local markets",
        "Production of bioethanol from agricultural waste (e.g., pineapple peels)",
        "Physicochemical and microbiological analysis of sachet water sold in Keffi",
        "Prevalence of antibiotic-resistant E. coli in water sources around livestock farms",
        "Enzymatic production of biodiesel from used cooking oil",
        "Assessment of heavy metal levels in edible vegetables from irrigated farmlands",
        "Probiotic potential of lactic acid bacteria isolated from kunu",
        "Phytochemical screening and antioxidant activity of common local spices",
        "Bioremediation potential of fungi isolated from hydrocarbon-polluted soil in Keffi",
    ],
    "Biochemistry": [
        "Antimicrobial activity of extracts from Azadirachta indica and Moringa against pathogens",
        "Production of bioethanol from agricultural waste materials",
        "Assessment of heavy metal levels in edible vegetables from irrigated farmlands",
        "Probiotic potential of lactic acid bacteria isolated from local beverages",
        "Phytochemical screening and antioxidant activity of common local spices",
        "Enzymatic production of biodiesel from used cooking oil",
        "Extraction and characterization of essential oils from lemongrass",
        "Analysis of trace metals in fish from the River Benue",
        "Proximate composition of honey from local beekeepers",
        "Nutritional analysis of underutilized indigenous food crops",
    ],
    "Chemistry": [
        "Extraction and characterization of essential oils from lemongrass grown in Nasarawa",
        "Formulation of herbal soap using Aloe vera and neem extracts",
        "Analysis of trace metals in fish from the River Benue",
        "Corrosion inhibition of mild steel using plant extracts",
        "Production of biodegradable plastic from cassava starch",
        "Quality assessment of different brands of vegetable oils sold in Lafia",
        "Determination of caffeine content in locally consumed tea and coffee",
        "Adsorption studies of dyes from solution using activated carbon from rice husks",
        "Analysis of physicochemical properties of honey from local beekeepers",
        "Synthesis and characterization of zeolites from kaolin for water purification",
    ],
    "Physics": [
        "Design and construction of a solar-powered water pumping system",
        "Assessment of groundwater potential in Keffi using geophysical methods",
        "Radon level measurement in dwellings around granite quarry sites",
        "Design of a low-cost wind turbine for rural electrification",
        "Analysis of satellite imagery for land use/land cover change in Nasarawa State",
        "Measurement of background radiation in selected locations of the state",
        "Fabrication of a simple dye-sensitized solar cell (DSSC)",
        "Geophysical investigation of subsurface structures for foundation integrity",
        "Analysis of meteorological data for rainfall pattern prediction in Lafia",
        "Design of energy-efficient lighting systems for rural communities",
    ],
    "Geology and Mining": [
        "Characterization of clay deposits in Nasarawa for ceramic production",
        "Geophysical investigation of subsurface structures for foundation integrity",
        "Assessment of groundwater potential using electrical resistivity methods",
        "Mapping of mineral resources distribution in selected areas of Nasarawa State",
        "Environmental impact assessment of mining activities on soil quality",
        "Petrographic analysis of rock samples from granite quarries",
        "Hydrogeological assessment of aquifer systems in Keffi",
        "Geological mapping and mineral prospecting in selected LGAs",
        "Assessment of slope stability in mining areas",
        "Water quality analysis around active and abandoned mine sites",
    ],
    "Mathematics": [
        "Mathematical modeling of malaria transmission dynamics in Nasarawa State",
        "Time series analysis of inflation rate in Nigeria (2000-2023)",
        "Statistical analysis of factors affecting student performance in UTME",
        "Application of queuing theory in optimizing bank service delivery",
        "Predictive model for crop yield based on rainfall and temperature data",
        "Statistical assessment of the prevalence of hypertension among adults in Keffi",
        "Optimization of transportation cost for a local food distribution company",
        "Demographic analysis of population growth and its projections for Nasarawa State",
        "Statistical quality control in a local production process",
        "Graph theory application in the design of efficient road networks within NASU",
    ],
    "Statistics": [
        "Time series analysis of inflation rate in Nigeria",
        "Statistical analysis of factors affecting student performance in UTME",
        "Statistical assessment of the prevalence of hypertension among adults",
        "Demographic analysis of population growth projections for Nasarawa State",
        "Statistical quality control in local production processes",
        "Survival analysis of patients with chronic diseases in tertiary hospitals",
        "Regression analysis of factors influencing agricultural productivity",
        "Multivariate analysis of socioeconomic factors affecting poverty",
        "Design and analysis of sample surveys for population studies",
        "Application of Bayesian methods in epidemiological research",
    ],
    "Plant Science and Biotechnology": [
        "Tissue culture propagation of economically important plant species",
        "Molecular characterization of local crop varieties using DNA markers",
        "Effect of plant growth regulators on in-vitro regeneration of cassava",
        "Genetic diversity assessment of indigenous yam varieties",
        "Micropropagation techniques for endangered medicinal plants",
        "Development of disease-resistant crop varieties through marker-assisted selection",
        "Phytoremediation potential of local plant species for heavy metal contamination",
        "Bioinformatics analysis of plant genome sequences",
        "Expression analysis of stress-related genes in drought-tolerant crops",
        "Development of biofertilizers from plant-associated microorganisms",
    ],
    
    # FACULTY OF SOCIAL SCIENCES
    "Political Science": [
        "The impact of social media on voter behavior in Nasarawa State (2023 election)",
        "Role of traditional institutions in conflict resolution in Nasarawa State",
        "An assessment of Nigeria's foreign policy towards the Sahel region",
        "The effectiveness of local government administration in rural development",
        "Gender and political participation in Nasarawa State",
        "The politics of solid mineral resource control in Nigeria",
        "ECOWAS and the management of democratic regression in West Africa",
        "Impact of herder-farmer conflicts on internal security in North-Central Nigeria",
        "China's Belt and Road Initiative and its implications for Nigeria's infrastructure",
        "Analysis of legislative oversight in Nigeria's Fourth Republic",
    ],
    "Mass Communication": [
        "Framing of farmer-herder conflicts in Nigerian newspapers",
        "Role of community radio in agricultural development in Nasarawa State",
        "Impact of social media influencers on the purchasing habits of NASU students",
        "Perception of fake news among rural dwellers in Nasarawa State",
        "Analysis of gender representation in Nigerian television adverts",
        "Use of public relations by NASU for its image management",
        "Audience perception of BBC Pidgin service in North-Central Nigeria",
        "Effectiveness of health communication campaigns on malaria prevention",
        "Comparative analysis of crisis reporting by online and traditional news platforms",
        "Film as a tool for cultural promotion: A study of Nollywood",
    ],
    "Economics": [
        "Impact of COVID-19 on small and medium enterprises (SMEs) in Lafia",
        "Effect of exchange rate volatility on import-dependent businesses in Nigeria",
        "Analysis of youth unemployment and its socioeconomic implications in Nasarawa State",
        "The relationship between government agricultural expenditure and food security",
        "Tax revenue and economic growth in Nigeria",
        "Poverty and income inequality in rural Nasarawa communities",
        "Impact of remittances from diaspora on household welfare",
        "Determinants of foreign direct investment (FDI) inflow into Nigeria",
        "Analysis of the effects of fuel subsidy removal on household consumption patterns",
        "The contribution of the solid minerals sector to Nasarawa State's GDP",
    ],
    "Sociology": [
        "Drug abuse and its social consequences among youths in Karu LGA",
        "Socio-cultural factors influencing girl-child education in Toto LGA",
        "Impact of internal displacement due to conflict on family structures",
        "Social media and its influence on marital stability among young couples",
        "Traditional birth attendants and maternal healthcare in rural areas",
        "Perception and stigma associated with mental illness in Keffi",
        "The role of social networks in rural-urban migration decisions",
        "Child labor in artisanal mining sites in Nasarawa",
        "Changing patterns of marriage rites among the Eggon people",
        "Sociology of campus cultism: A case study of NASU",
    ],
    "Psychology": [
        "Stress levels and coping strategies among final-year students of NASU",
        "Effect of social media addiction on academic performance",
        "Relationship between parenting styles and adolescent self-esteem",
        "Prevalence of depression among healthcare workers in public hospitals",
        "Impact of color on consumer buying behavior in supermarkets",
        "Psychological effects of prolonged unemployment on graduates",
        "Perception of domestic violence among married adults",
        "Correlation between personality traits and career choice among undergraduates",
        "Study habits and academic achievement in science and arts students",
        "Attitudes of students towards people with physical disabilities",
    ],
    
    # FACULTY OF ARTS
    "English Language": [
        "A stylistic analysis of selected political speeches",
        "Code-switching and code-mixing in Nigerian hip-hop music",
        "Feminist critique of selected works of a Nigerian female novelist",
        "Discourse analysis of gender representation in Nigerian textbooks",
        "Documentation of oral poetry of a minority ethnic group in Nasarawa",
        "Language of social media communication among Nigerian youths",
        "A contrastive analysis of English and Gwandara tense systems",
        "Pidgin English as a tool for national integration in Nigeria",
        "Study of neologisms in Nigerian English",
        "The theme of conflict in contemporary Nigerian drama",
    ],
    "History": [
        "History of the Alago people: Migration and settlement",
        "Impact of colonial rule on the traditional political system of the Eggon",
        "The role of Nasarawa State in Nigeria's civil war (1967-1970)",
        "Historical analysis of inter-group relations in the Middle Belt",
        "History of educational development in Nasarawa State (1996-date)",
        "Biographical study of a prominent traditional ruler in Nasarawa",
        "The evolution of Keffi from a pre-colonial town to a modern city",
        "Historical assessment of the mining industry in Nasarawa",
        "Nigeria's role in peacekeeping missions in Africa: A case study of Liberia",
        "The impact of Islam and Christianity on the culture of the Mada people",
    ],
    "Christian Religious Studies": [
        "Inter-religious dialogue as a tool for peacebuilding in conflict-prone communities",
        "The impact of Pentecostalism on moral values among youths in Karu",
        "Comparative analysis of burial rites in Islam and Christianity in Nasarawa",
        "The role of religious leaders in mitigating farmer-herder conflicts",
        "Trends in church growth and development in Keffi (2000-2023)",
        "The concept of peace in the Quran and the Bible",
        "Influence of African Traditional Religion on the practice of Christianity",
        "Religion and politics in Nigeria's Fourth Republic",
        "The phenomenon of religious pilgrimage: Economic and social impacts",
        "Biblical perspectives on environmental stewardship",
    ],
    "Islamic Studies": [
        "The role of Islamic education in moral development of youth",
        "Comparative analysis of burial rites in Islam and Christianity",
        "The role of religious leaders in mitigating farmer-herder conflicts",
        "The concept of peace in Islamic teachings",
        "Doctrinal differences among major Islamic sects in Nasarawa State",
        "The impact of Islamic banking on financial inclusion in Nigeria",
        "Islamic perspectives on environmental conservation",
        "The contribution of Islamic scholars to the development of Nasarawa State",
        "Analysis of Zakat collection and distribution in Nasarawa State",
        "Islamic family law and its application in Nigerian courts",
    ],
    "Arabic Studies": [
        "The influence of Arabic on the Hausa language in Nasarawa State",
        "Analysis of Arabic inscriptions in historical mosques of North-Central Nigeria",
        "Translation challenges of Arabic religious texts into Nigerian languages",
        "The role of Arabic in Islamic education in Nasarawa State",
        "Contribution of Arabic scholars to the intellectual history of Nasarawa",
        "Comparative study of Arabic dialects spoken in Nigerian Islamic schools",
        "Arabic literature and its influence on Nigerian Muslim writers",
        "The teaching of Arabic as a second language in Nigerian universities",
        "Arabic calligraphy as an art form in Nigerian mosques",
        "The impact of Arabic media on language learning in Nigeria",
    ],
    "French": [
        "The role of French in Nigeria's foreign policy towards Francophone neighbors",
        "Challenges of teaching French as a foreign language in Nigerian secondary schools",
        "Translation issues in French-Nigerian diplomatic communications",
        "The influence of French culture on Nigerian fashion and cuisine",
        "Comparative analysis of educational systems in Nigeria and Francophone West Africa",
        "French language proficiency and employment opportunities in Nigeria",
        "The impact of Nigerian migrants in Francophone countries on cultural exchange",
        "Analysis of Nigerian literature translated into French",
        "The role of Alliance Française in promoting French language in Nigeria",
        "Code-switching patterns among French language learners in NASU",
    ],
    "Theatre and Cultural Studies": [
        "Traditional festivals as a medium for cultural preservation in Nasarawa State",
        "The role of community theatre in development communication",
        "Analysis of Nollywood's representation of ethnic minorities",
        "Documentation and analysis of traditional dance forms of the Eggon people",
        "Theatre for development: A tool for health education in rural communities",
        "The impact of digital technology on Nigerian theatre production",
        "Costume and makeup design in traditional Nigerian performances",
        "The economics of cultural tourism in Nasarawa State",
        "Gender roles in traditional Nasarawa theatre",
        "Contemporary adaptations of Nigerian folktales for stage performance",
    ],
    
    # FACULTY OF EDUCATION
    "Education and Biology": [
        "Effect of instructional materials on teaching and learning of biology",
        "Impact of laboratory practical sessions on students' understanding of biology",
        "Assessment of the biology curriculum and its relevance to local needs",
        "Comparative study of biology achievement in urban and rural schools",
        "Effect of concept mapping on students' performance in genetics",
        "Teachers' perception of the new biology curriculum content",
        "Relationship between students' attitude and performance in biology",
        "Effect of peer tutoring on academic achievement in biology",
        "Analysis of biology questions in WAEC examinations",
        "Integration of ICT in biology teaching and learning",
    ],
    "Education and Chemistry": [
        "Effect of demonstration method on students' performance in chemistry",
        "Assessment of laboratory facilities for chemistry teaching in secondary schools",
        "Students' misconceptions in balancing chemical equations",
        "Effect of computer simulation on teaching chemical bonding",
        "Relationship between mathematical ability and chemistry performance",
        "Analysis of difficult topics in chemistry according to students and teachers",
        "Effect of practical work on students' interest in chemistry",
        "Gender differences in chemistry achievement in Nasarawa State",
        "Evaluation of chemistry textbooks used in secondary schools",
        "Strategies for improving performance in chemistry practical examinations",
    ],
    "Education and Mathematics": [
        "Effect of gender on students' academic achievement in mathematics",
        "Impact of instructional materials on teaching and learning of mathematics",
        "Assessment of factors affecting students' performance in mathematics",
        "Effect of class size on effective teaching and learning of mathematics",
        "Students' perception towards the study of mathematics",
        "Comparative analysis of mathematics achievement using different teaching methods",
        "The role of parental involvement in students' mathematics performance",
        "Assessment of mathematics anxiety among secondary school students",
        "Effect of problem-based learning on students' interest in mathematics",
        "Analysis of common errors in solving algebraic equations",
    ],
    "Education and Physics": [
        "Perception of students towards the study of physics",
        "Effect of practical activities on students' understanding of physics concepts",
        "Assessment of physics laboratory equipment in secondary schools",
        "Students' difficulties in understanding electromagnetic concepts",
        "Effect of computer-assisted instruction on physics achievement",
        "Gender differences in physics performance and interest",
        "Analysis of physics questions in national examinations",
        "Strategies for improving enrollment in physics classes",
        "The relationship between physics knowledge and career choice",
        "Integration of real-world applications in physics teaching",
    ],
    "Education and English Language": [
        "Challenges facing the teaching of English language in rural primary schools",
        "Effect of mother tongue interference on English pronunciation",
        "Assessment of reading comprehension skills among secondary school students",
        "Strategies for improving essay writing skills",
        "The role of language laboratory in English language teaching",
        "Students' attitude towards English language learning",
        "Error analysis in students' written composition",
        "Effect of drama activities on English language proficiency",
        "Assessment of English language textbooks for appropriateness",
        "The impact of social media on students' English writing skills",
    ],
    "Education and Economics": [
        "Effect of class size on effective teaching and learning of economics",
        "Assessment of factors affecting students' performance in economics",
        "Students' perception towards the study of economics",
        "Impact of teaching aids on students' achievement in economics",
        "Comparative study of economics achievement in public and private schools",
        "The relationship between economic literacy and financial behavior of students",
        "Analysis of economics curriculum for relevance to current economic realities",
        "Effect of field trips on students' understanding of economic concepts",
        "Assessment of economics practical projects in secondary schools",
        "Gender differences in economics performance in NASU",
    ],
    "Education and Geography": [
        "Effect of field trips on students' understanding of geography concepts",
        "Assessment of geography teaching resources in secondary schools",
        "Students' difficulties in map reading and interpretation",
        "Impact of GIS technology on geography education",
        "The role of geography education in environmental awareness",
        "Comparative analysis of geography curricula in Nigeria and other countries",
        "Effect of climate change education on students' environmental behavior",
        "Assessment of geography examination questions for cognitive levels",
        "Strategies for improving interest in physical geography topics",
        "Integration of local examples in geography teaching",
    ],
    "Education and History": [
        "Challenges of teaching history in Nigerian secondary schools",
        "Students' perception of history as a subject of study",
        "The use of primary sources in history teaching",
        "Assessment of history textbooks for accuracy and balance",
        "Effect of storytelling method on students' interest in history",
        "The role of history education in national identity formation",
        "Integration of local history in the secondary school curriculum",
        "Students' understanding of historical thinking skills",
        "The impact of digital resources on history teaching and learning",
        "Assessment of history questions in WAEC for cognitive demand",
    ],
    "Education and Christian Religious Studies": [
        "Effect of values education on moral behavior of students",
        "Assessment of Christian Religious Studies curriculum content",
        "Students' perception of Christian Religious Studies as a subject",
        "The role of religious education in character development",
        "Comparative study of religious education in public and faith-based schools",
        "Challenges of teaching religious pluralism in CRS classes",
        "Integration of community service in Christian Religious Studies",
        "Assessment of CRS textbooks for doctrinal accuracy and inclusivity",
        "The impact of religious instruction on students' social behavior",
        "Strategies for making CRS relevant to contemporary issues",
    ],
    "Education and Islamic Studies": [
        "Assessment of Islamic Studies curriculum in Nigerian secondary schools",
        "Students' perception of Islamic Studies as a subject of study",
        "The role of Islamic education in moral development",
        "Challenges of teaching Islamic Studies in multi-religious settings",
        "Integration of contemporary issues in Islamic Studies curriculum",
        "Effect of memorization techniques on Quranic recitation skills",
        "Assessment of Arabic language competency among Islamic Studies students",
        "The role of Islamic schools in educational development",
        "Comparative study of Islamic education in Nigeria and other countries",
        "Strategies for improving interest in Islamic Studies",
    ],
    "Education and French": [
        "Challenges of teaching French in Nigerian secondary schools",
        "Students' attitude towards learning French as a foreign language",
        "Assessment of French language teaching resources",
        "Effect of immersion programs on French language proficiency",
        "The role of French language in career opportunities for Nigerian graduates",
        "Comparative analysis of French teaching methods",
        "Integration of technology in French language teaching",
        "Assessment of French language examinations for communicative competence",
        "Strategies for improving French pronunciation among Nigerian learners",
        "The impact of cultural awareness on French language learning",
    ],
    "Education and Integrated Science": [
        "Assessment of integrated science curriculum for interdisciplinary connections",
        "Effect of practical activities on integrated science achievement",
        "Students' perception of integrated science as a foundational subject",
        "Challenges of teaching integrated science in rural primary schools",
        "The role of integrated science in preparing students for senior science subjects",
        "Assessment of integrated science textbooks for accuracy and appropriateness",
        "Effect of inquiry-based learning on integrated science performance",
        "Integration of environmental education in integrated science teaching",
        "Gender differences in interest and performance in integrated science",
        "Strategies for improving practical skills in integrated science",
    ],
    
    # FACULTY OF ADMINISTRATION
    "Accounting": [
        "Impact of computerized accounting on financial reporting accuracy",
        "Analysis of internal control systems in public sector organizations",
        "Effect of forensic accounting on fraud detection in Nigerian banks",
        "Assessment of accounting students' readiness for professional practice",
        "The role of management accounting in decision making of SMEs",
        "Impact of IFRS adoption on financial statements of Nigerian companies",
        "Tax compliance behavior of small businesses in Nasarawa State",
        "Effect of corporate governance on financial performance of listed companies",
        "Analysis of cost accounting practices in manufacturing firms",
        "The role of budgeting in financial management of local governments",
    ],
    "Business Administration": [
        "Impact of entrepreneurship education on business startup intentions",
        "Effect of leadership styles on employee performance in banking sector",
        "Analysis of customer relationship management practices in Nigerian businesses",
        "Strategic planning and organizational performance in SMEs",
        "The role of e-commerce in business growth in Nasarawa State",
        "Impact of COVID-19 on business operations and survival strategies",
        "Human resource management practices in Nigerian public organizations",
        "Effect of organizational culture on employee productivity",
        "Marketing strategies for promoting local agricultural products",
        "Supply chain management challenges in Nigerian manufacturing firms",
    ],
    "Public Administration": [
        "Assessment of e-governance implementation in Nasarawa State",
        "The effectiveness of local government administration in rural development",
        "Impact of civil service reforms on public sector performance",
        "Analysis of public policy implementation challenges in Nigeria",
        "The role of traditional institutions in local governance",
        "Assessment of performance management systems in public organizations",
        "Impact of political interference on civil service efficiency",
        "Analysis of bureaucratic bottlenecks in license and permit processing",
        "The role of public-private partnerships in infrastructure development",
        "Assessment of transparency and accountability in public financial management",
    ],
    "Banking and Finance": [
        "Impact of mobile banking on financial inclusion in rural areas",
        "Analysis of credit risk management practices in Nigerian banks",
        "Effect of interest rate policies on bank lending behavior",
        "Assessment of microfinance institutions in poverty alleviation",
        "The role of financial technology (FinTech) in banking sector transformation",
        "Impact of bank consolidation on competitive performance",
        "Analysis of foreign exchange management in Nigerian banks",
        "Effect of corporate governance on bank performance",
        "Assessment of agricultural financing by commercial banks",
        "The role of development finance institutions in economic development",
    ],
    "Entrepreneurship Studies": [
        "Factors influencing entrepreneurial intentions among university students",
        "Assessment of government support programs for young entrepreneurs",
        "The role of business incubators in startup success",
        "Challenges facing women entrepreneurs in Nasarawa State",
        "Impact of entrepreneurship education on self-employment decisions",
        "Analysis of innovation practices among small business owners",
        "The role of social capital in entrepreneurial success",
        "Assessment of funding sources for new business ventures",
        "Entrepreneurial opportunities in agricultural value chains",
        "Impact of mentorship on entrepreneurial business growth",
    ],
    
    # FACULTY OF LAW
    "Law": [
        "Analysis of land rights and tenure security in Nasarawa State",
        "The legal framework for environmental protection in Nigeria",
        "Assessment of alternative dispute resolution mechanisms for farmer-herder conflicts",
        "Human rights implications of internally displaced persons in Nigeria",
        "Legal challenges of e-commerce in Nigeria",
        "Analysis of intellectual property protection for traditional knowledge",
        "The effectiveness of anti-corruption legislation in Nigeria",
        "Legal aspects of corporate governance in Nigerian companies",
        "Assessment of consumer protection laws and their enforcement",
        "The legal framework for public-private partnerships in Nigeria",
    ],
    
    # FACULTY OF ENVIRONMENTAL SCIENCE
    "Environmental Management": [
        "Assessment of solid waste management practices in Keffi",
        "Environmental impact assessment of mining activities in Nasarawa State",
        "Analysis of air quality in urban areas of Lafia",
        "Water resource management and sustainable development",
        "Assessment of deforestation and its impact on local climate",
        "Climate change adaptation strategies among farmers",
        "Environmental awareness and behavior among university students",
        "Assessment of pollution levels in major rivers of Nasarawa State",
        "The role of environmental NGOs in conservation efforts",
        "Sustainable solid waste management through recycling initiatives",
    ],
    "Architecture": [
        "Sustainable building design for hot climatic conditions in Nasarawa",
        "Traditional architecture and its adaptation to modern needs",
        "Assessment of housing quality in low-income urban settlements",
        "Energy-efficient design strategies for public buildings",
        "The role of green spaces in urban planning of Keffi",
        "Adaptive reuse of historical buildings for contemporary functions",
        "Assessment of accessibility features in public buildings",
        "Sustainable materials for affordable housing construction",
        "Analysis of urban sprawl and its impact on architectural planning",
        "Bioclimatic design principles for educational buildings",
    ],
    "Geography": [
        "Land use and land cover change analysis using remote sensing",
        "Assessment of urban growth patterns in Lafia",
        "Geographic information systems for infrastructure planning",
        "Climate variability and its impact on agricultural production",
        "Analysis of settlement patterns in rural Nasarawa",
        "Geographic analysis of healthcare facility distribution",
        "Assessment of flood-prone areas using GIS techniques",
        "Transportation network analysis for improved accessibility",
        "Soil mapping for agricultural zonation",
        "Population distribution and migration patterns in Nasarawa State",
    ],
    "Urban and Regional Planning": [
        "Assessment of informal settlements and upgrading strategies",
        "Transportation planning for sustainable urban mobility",
        "Land use planning for balanced urban development",
        "Assessment of recreational facilities in urban areas",
        "Housing policy analysis and affordable housing provision",
        "Urban renewal strategies for declining city centers",
        "Regional development planning for balanced growth",
        "Assessment of urban infrastructure and service delivery",
        "Community participation in urban planning processes",
        "Smart city concepts and their applicability in Nigerian cities",
    ],
    
    # FACULTY OF MEDICAL AND HEALTH SCIENCES
    "Nursing": [
        "Assessment of nursing care quality in public hospitals",
        "Factors affecting job satisfaction among nurses in Nasarawa State",
        "Knowledge and practice of infection control among nursing students",
        "Assessment of maternal healthcare services in primary health centers",
        "The role of nurses in health education and disease prevention",
        "Challenges facing nursing practice in rural health facilities",
        "Assessment of patient satisfaction with nursing care",
        "Knowledge and attitude of nurses towards palliative care",
        "The impact of nurse staffing levels on patient outcomes",
        "Assessment of nursing documentation practices in hospitals",
    ],
}

# Default topics for departments not specifically listed
DEFAULT_TOPICS = [
    "Analysis of current trends and challenges in your field of study",
    "Impact of technology adoption on practices in your discipline",
    "Assessment of professional development needs in your field",
    "Comparative study of local and international best practices",
    "The role of education and training in improving sector outcomes",
    "Sustainability considerations in your discipline",
    "Policy analysis and recommendations for your field",
    "Case study analysis of successful projects in your area",
    "Stakeholder perspectives on key issues in your discipline",
    "Future trends and predictions for your field of study",
]
