# projects/topic_data.py
# Department-specific project topics for the Topic Generator

DEPARTMENT_TOPICS = {
    # FACULTY OF AGRICULTURE
    "Agricultural Economics and Extension": [
        "Economic analysis of sesame seed marketing chain in Nasarawa State",
        "Impact of Fadama III project on income of rice farmers in Lafia",
        "Adoption rate of improved cassava varieties among smallholder farmers in Kokona LGA",
        "Profitability and constraints of small-scale poultry egg production in Keffi",
        "Effects of herder-farmer conflicts on agricultural productivity in Obi LGA",
        "Willingness to pay for agricultural insurance by crop farmers in Nasarawa State",
        "Role of social media in agricultural information dissemination among youth farmers",
        "Gender analysis of access to agricultural credits in Doma LGA",
        "Value chain analysis of yam production and its post-harvest losses",
        "Impact of climate change perception on farming practices in the Southern Zone",
        # Additional topics
        "Analysis of the efficiency of input subsidy programs on smallholder farmers' productivity",
        "Economic impact of post-harvest losses on tomato farmers in Nasarawa State",
        "Assessment of agricultural extension service delivery methods in rural communities",
        "Role of microfinance institutions in agricultural financing among women farmers",
        "Comparative analysis of organic and conventional farming systems profitability",
        "Impact of climate-smart agricultural practices on farmers' resilience",
        "Value chain mapping and analysis for maize production in Nasarawa West",
        "Assessment of youth participation in commercial agriculture",
        "Economic analysis of snail farming as an alternative income source",
        "Effect of transportation costs on agricultural product pricing in local markets",
    ],
    "Agronomy": [
        "Response of local maize variety to different organic fertilizers (poultry manure, compost)",
        "Evaluation of soybean genotypes for drought tolerance in the Keffi environment",
        "Effect of planting dates on the growth and yield of sweet potato",
        "Weed management strategies in upland rice cultivation",
        "Seed viability and germination tests for indigenous vegetable seeds",
        "Intercropping compatibility of cassava and groundnut",
        "Soil amendment using biochar from rice husks for tomato production",
        "Assessment of soil fertility status in selected farmlands in Nasarawa West",
        "Control of Striga (witchweed) in sorghum fields using cultural methods",
        "Growth performance of Moringa oleifera under different pruning regimes",
        # Additional topics
        "Effect of different irrigation methods on water use efficiency in vegetable production",
        "Assessment of improved maize varieties for adaptation to local growing conditions",
        "Soil nutrient management using integrated plant nutrition system approach",
        "Evaluation of mulching materials on soil moisture conservation and crop yield",
        "Phenological studies of indigenous crop varieties under changing climatic conditions",
        "Assessment of alley cropping systems for soil fertility improvement",
        "Effect of minimum tillage practices on soil structure and crop productivity",
        "Evaluation of cover crops for weed suppression in cereal production",
        "Assessment of crop rotation systems for pest and disease management",
        "Effect of plant spacing on yield and yield components of cowpea varieties",
    ],
    "Animal Science": [
        "Carcass characteristics of broiler chickens fed diets containing Moringa oleifera leaf meal",
        "Effects of replacing maize with fermented cassava peels in rabbit diets",
        "Assessment of ethno-veterinary practices among Fulani herdsmen in Nasarawa State",
        "Semen quality analysis of local turkey cocks supplemented with selenium",
        "Prevalence of gastrointestinal parasites in locally reared goats in Keffi",
        "Milk production and composition of White Fulani cows under semi-intensive system",
        "Haematological parameters of broilers fed neem leaf extract as an antibiotic alternative",
        "Feed intake and growth performance of pigs fed watermelon rind meal",
        "Characterization of local chicken ecotypes in Nasarawa State",
        "Effects of housing density on stress indicators in layers",
        # Additional topics
        "Assessment of artificial insemination success rate in dairy cattle in Nasarawa State",
        "Evaluation of different protein sources in fish feed formulation",
        "Effect of housing systems on behavioral patterns and welfare of poultry",
        "Assessment of meat quality parameters in different indigenous poultry breeds",
        "Evaluation of forage conservation methods for dry season feeding of ruminants",
        "Effect of probiotic supplementation on growth performance of weaner pigs",
        "Assessment of reproductive performance of rabbit breeds under local conditions",
        "Evaluation of different litter materials on broiler production parameters",
        "Assessment of zoonotic disease transmission risks at livestock markets",
        "Effect of breed and management system on egg quality characteristics",
    ],
    "Forestry, Wildlife and Ecotourism": [
        "Growth performance of Clarias gariepinus (catfish) fed household food waste diet",
        "Water quality assessment of selected fish ponds in Lafia",
        "Economic analysis of artisanal fishing in the River Benue (Nasarawa segment)",
        "Prevalence of fish parasites in Lake Nasarawa",
        "Effect of stocking density on survival rate of Nile tilapia in concrete tanks",
        "Proximate composition of smoked fish using different local smoking kilns",
        "Potential of duckweed (Lemna minor) as feed for tilapia fingerlings",
        "Assessment of fish farming adoption among youth in Doma",
        "Reproductive performance of African catfish induced with different hormones",
        "Design and construction of a low-cost water recirculation system for aquaponics",
        # Additional topics
        "Assessment of community-based forest management practices in Nasarawa State",
        "Evaluation of wildlife tourism potential in selected protected areas",
        "Impact of logging activities on bird species diversity in forest reserves",
        "Assessment of non-timber forest products utilization by rural communities",
        "Evaluation of mangrove restoration techniques in coastal areas",
        "Assessment of ecotourism infrastructure development needs in tourist sites",
        "Evaluation of participatory forest management approaches",
        "Assessment of carbon sequestration potential of different forest types",
        "Impact of climate change on forest tree species distribution",
        "Evaluation of agroforestry systems for sustainable land use",
    ],
    "Home Science and Management": [
        "Mapping of soil erosion prone areas in Nasarawa State using GIS",
        "Effects of different mulch types on soil moisture conservation and maize yield",
        "Physico-chemical properties of soils around solid mineral mining sites in Nasarawa",
        "Carbon sequestration potential of soils under different land use systems",
        "Assessment of heavy metal contamination in vegetables grown along major highways",
        "Soil suitability evaluation for citrus production in the Northern Zone",
        "Effect of long-term fertilizer application on soil pH and microbial activity",
        "Use of sawdust ash as a liming material for acid soils",
        "Assessment of irrigation water quality from shallow wells in agrarian communities",
        "Land capability classification for selected areas in Keffi",
        # Additional topics
        "Assessment of soil conservation practices among farmers in erosion-prone areas",
        "Evaluation of integrated soil fertility management approaches",
        "Impact of land use changes on soil organic carbon stocks",
        "Assessment of soil salinity problems in irrigated agricultural areas",
        "Evaluation of soil amendment materials for reclaiming degraded lands",
        "Assessment of soil biodiversity under different agricultural management systems",
        "Impact of climate change on soil erosion risks",
        "Evaluation of precision agriculture technologies for soil management",
        "Assessment of soil nutrient balance in smallholder farming systems",
        "Evaluation of remote sensing techniques for soil moisture monitoring",
    ],
    
    # FACULTY OF NATURAL AND APPLIED SCIENCES
    "Computer Science": [
        "Design and implementation of a web-based farm produce marketplace for Nasarawa State",
        "Development of a mobile app for reporting and tracking farmer-herder conflicts (GIS-based)",
        "NASU E-Campus: An enhanced student portal with integrated lecture notes and forum features",
        "Predictive model for student academic performance using machine learning",
        "Automated system for detecting fake news in Nigerian social media spaces",
        "Design of a biometric-based attendance management system for university staff",
        "Sentiment analysis of public opinion on government policies from Twitter data",
        "Development of an offline-capable educational app for secondary school STEM subjects",
        "Network intrusion detection system using deep learning techniques",
        "Design of a virtual reality (VR) tour of Nasarawa State University",
        # Additional topics
        "Development of an AI-powered chatbot for university admission inquiries",
        "Blockchain-based certificate verification system for academic institutions",
        "IoT-based smart agriculture monitoring system for smallholder farmers",
        "Development of a mobile health (mHealth) application for maternal care",
        "Cybersecurity threat assessment framework for Nigerian financial institutions",
        "Natural language processing system for Nigerian local languages",
        "Development of a recommendation system for academic research papers",
        "Cloud-based collaborative platform for student project management",
        "Image recognition system for plant disease detection",
        "Development of a gamified e-learning platform for programming education",
    ],
    "Microbiology": [
        "Antimicrobial activity of extracts from local plants against wound pathogens",
        "Mycoflora and aflatoxin contamination of stored grains in local markets",
        "Production of bioethanol from agricultural waste (e.g., pineapple peels)",
        "Physicochemical and microbiological analysis of sachet water sold in Keffi",
        "Prevalence of antibiotic-resistant E. coli in water sources around livestock farms",
        "Enzymatic production of biodiesel from used cooking oil",
        "Assessment of heavy metal levels in edible vegetables from irrigated farmlands",
        "Probiotic potential of lactic acid bacteria isolated from kunu",
        "Phytochemical screening and antioxidant activity of common local spices",
        "Bioremediation potential of fungi isolated from hydrocarbon-polluted soil in Keffi",
        # Additional topics
        "Microbial diversity assessment in different soil types of Nasarawa State",
        "Production of single-cell protein from agricultural by-products",
        "Assessment of microbial quality of street-vended foods in Keffi",
        "Isolation and characterization of thermophilic bacteria from hot springs",
        "Development of microbial biofertilizers for sustainable agriculture",
        "Antibiotic susceptibility patterns of clinical bacterial isolates",
        "Microbial production of industrial enzymes from organic wastes",
        "Assessment of biofilm formation by pathogenic bacteria on medical devices",
        "Microbial degradation of plastic wastes in the environment",
        "Development of rapid diagnostic tests for common infectious diseases",
    ],
    "Biochemistry": [
        "Antimicrobial activity of extracts from Azadirachta indica and Moringa against pathogens",
        "Production of bioethanol from agricultural waste materials",
        "Assessment of heavy metal levels in edible vegetables from irrigated farmlands",
        "Probiotic potential of lactic acid bacteria isolated from local beverages",
        "Phytochemical screening and antioxidant activity of common local spices",
        "Enzymatic production of biodiesel from used cooking oil",
        "Extraction and characterization of essential oils from lemongrass",
        "Analysis of trace metals in fish from the River Benue",
        "Proximate composition of honey from local beekeepers",
        "Nutritional analysis of underutilized indigenous food crops",
        # Additional topics
        "Biochemical characterization of enzymes from extremophilic microorganisms",
        "Assessment of oxidative stress markers in chronic disease patients",
        "Production of bioplastics from renewable resources",
        "Analysis of bioactive compounds in medicinal plants used traditionally",
        "Development of functional foods from local ingredients",
        "Assessment of nutritional status of school children in rural areas",
        "Biochemical basis of drug interactions and side effects",
        "Production of biosurfactants from microbial sources",
        "Analysis of food adulteration in commonly consumed products",
        "Development of rapid diagnostic kits for metabolic disorders",
    ],
    "Chemistry": [
        "Extraction and characterization of essential oils from lemongrass grown in Nasarawa",
        "Formulation of herbal soap using Aloe vera and neem extracts",
        "Analysis of trace metals in fish from the River Benue",
        "Corrosion inhibition of mild steel using plant extracts",
        "Production of biodegradable plastic from cassava starch",
        "Quality assessment of different brands of vegetable oils sold in Lafia",
        "Determination of caffeine content in locally consumed tea and coffee",
        "Adsorption studies of dyes from solution using activated carbon from rice husks",
        "Analysis of physicochemical properties of honey from local beekeepers",
        "Synthesis and characterization of zeolites from kaolin for water purification",
        # Additional topics
        "Development of natural dyes from plant sources for textile industry",
        "Synthesis and characterization of nanoparticles for drug delivery",
        "Analysis of pesticide residues in agricultural products",
        "Development of water purification tablets for emergency situations",
        "Synthesis of biodegradable polymers from renewable resources",
        "Analysis of nutritional supplements for quality and authenticity",
        "Development of eco-friendly corrosion inhibitors",
        "Synthesis of metal-organic frameworks for gas storage",
        "Analysis of cosmetics for heavy metal contamination",
        "Development of electrochemical sensors for environmental monitoring",
    ],
    "Physics": [
        "Design and construction of a solar-powered water pumping system",
        "Assessment of groundwater potential in Keffi using geophysical methods",
        "Radon level measurement in dwellings around granite quarry sites",
        "Design of a low-cost wind turbine for rural electrification",
        "Analysis of satellite imagery for land use/land cover change in Nasarawa State",
        "Measurement of background radiation in selected locations of the state",
        "Fabrication of a simple dye-sensitized solar cell (DSSC)",
        "Geophysical investigation of subsurface structures for foundation integrity",
        "Analysis of meteorological data for rainfall pattern prediction in Lafia",
        "Design of energy-efficient lighting systems for rural communities",
        # Additional topics
        "Development of a solar dryer for agricultural products",
        "Assessment of indoor air quality in different building types",
        "Design and construction of a solar cooker",
        "Analysis of wind energy potential in selected locations",
        "Development of a weather monitoring station using IoT",
        "Assessment of noise pollution levels in urban areas",
        "Fabrication of piezoelectric energy harvesters",
        "Analysis of optical properties of thin films",
        "Development of a low-cost water quality monitoring system",
        "Assessment of electromagnetic radiation from mobile phone towers",
    ],
    "Geology and Mining": [
        "Characterization of clay deposits in Nasarawa for ceramic production",
        "Geophysical investigation of subsurface structures for foundation integrity",
        "Assessment of groundwater potential using electrical resistivity methods",
        "Mapping of mineral resources distribution in selected areas of Nasarawa State",
        "Environmental impact assessment of mining activities on soil quality",
        "Petrographic analysis of rock samples from granite quarries",
        "Hydrogeological assessment of aquifer systems in Keffi",
        "Geological mapping and mineral prospecting in selected LGAs",
        "Assessment of slope stability in mining areas",
        "Water quality analysis around active and abandoned mine sites",
        # Additional topics
        "Assessment of geotechnical properties of soils for construction purposes",
        "Evaluation of geothermal energy potential in selected areas",
        "Analysis of seismic hazard and risk assessment",
        "Characterization of industrial minerals for economic development",
        "Assessment of coastal erosion and mitigation measures",
        "Evaluation of groundwater vulnerability to contamination",
        "Analysis of sediment transport in river systems",
        "Assessment of geological factors affecting dam construction",
        "Evaluation of mineral processing techniques for local ores",
        "Analysis of geological controls on groundwater flow",
    ],
    "Mathematics": [
        "Mathematical modeling of malaria transmission dynamics in Nasarawa State",
        "Time series analysis of inflation rate in Nigeria (2000-2023)",
        "Statistical analysis of factors affecting student performance in UTME",
        "Application of queuing theory in optimizing bank service delivery",
        "Predictive model for crop yield based on rainfall and temperature data",
        "Statistical assessment of the prevalence of hypertension among adults in Keffi",
        "Optimization of transportation cost for a local food distribution company",
        "Demographic analysis of population growth and its projections for Nasarawa State",
        "Statistical quality control in a local production process",
        "Graph theory application in the design of efficient road networks within NASU",
        # Additional topics
        "Mathematical modeling of COVID-19 spread and intervention strategies",
        "Fuzzy logic applications in decision support systems",
        "Numerical analysis of heat transfer in engineering systems",
        "Mathematical modeling of stock price movements",
        "Optimization algorithms for resource allocation problems",
        "Statistical analysis of crime patterns and prediction",
        "Mathematical modeling of traffic flow in urban areas",
        "Game theory applications in economic decision making",
        "Numerical methods for solving differential equations in engineering",
        "Statistical analysis of sports performance data",
    ],
    "Statistics": [
        "Time series analysis of inflation rate in Nigeria",
        "Statistical analysis of factors affecting student performance in UTME",
        "Statistical assessment of the prevalence of hypertension among adults",
        "Demographic analysis of population growth projections for Nasarawa State",
        "Statistical quality control in local production processes",
        "Survival analysis of patients with chronic diseases in tertiary hospitals",
        "Regression analysis of factors influencing agricultural productivity",
        "Multivariate analysis of socioeconomic factors affecting poverty",
        "Design and analysis of sample surveys for population studies",
        "Application of Bayesian methods in epidemiological research",
        # Additional topics
        "Statistical analysis of customer satisfaction survey data",
        "Risk assessment models for insurance companies",
        "Statistical process control in manufacturing industries",
        "Analysis of variance in agricultural field experiments",
        "Statistical modeling of climate change impacts",
        "Reliability analysis of engineering systems",
        "Statistical analysis of marketing campaign effectiveness",
        "Design of experiments for product development",
        "Statistical analysis of social media engagement metrics",
        "Forecasting models for economic indicators",
    ],
    "Plant Science and Biotechnology": [
        "Tissue culture propagation of economically important plant species",
        "Molecular characterization of local crop varieties using DNA markers",
        "Effect of plant growth regulators on in-vitro regeneration of cassava",
        "Genetic diversity assessment of indigenous yam varieties",
        "Micropropagation techniques for endangered medicinal plants",
        "Development of disease-resistant crop varieties through marker-assisted selection",
        "Phytoremediation potential of local plant species for heavy metal contamination",
        "Bioinformatics analysis of plant genome sequences",
        "Expression analysis of stress-related genes in drought-tolerant crops",
        "Development of biofertilizers from plant-associated microorganisms",
        # Additional topics
        "Production of secondary metabolites from plant cell cultures",
        "Molecular diagnostics for plant pathogens",
        "Development of transgenic plants with improved traits",
        "Assessment of genetically modified organisms (GMOs) impacts",
        "Plant metabolomics for quality assessment of medicinal plants",
        "Development of molecular markers for trait selection",
        "Plant-microbe interactions for sustainable agriculture",
        "Proteomic analysis of plant stress responses",
        "Development of biosensors for plant disease detection",
        "Conservation of plant genetic resources through biotechnological approaches",
    ],
    
    # FACULTY OF SOCIAL SCIENCES
    "Political Science": [
        "The impact of social media on voter behavior in Nasarawa State (2023 election)",
        "Role of traditional institutions in conflict resolution in Nasarawa State",
        "An assessment of Nigeria's foreign policy towards the Sahel region",
        "The effectiveness of local government administration in rural development",
        "Gender and political participation in Nasarawa State",
        "The politics of solid mineral resource control in Nigeria",
        "ECOWAS and the management of democratic regression in West Africa",
        "Impact of herder-farmer conflicts on internal security in North-Central Nigeria",
        "China's Belt and Road Initiative and its implications for Nigeria's infrastructure",
        "Analysis of legislative oversight in Nigeria's Fourth Republic",
        # Additional topics
        "The role of civil society organizations in democratic consolidation",
        "Analysis of electoral reforms and their impact on election credibility",
        "Youth political participation and representation in Nigeria",
        "The politics of resource allocation and development in Nigeria",
        "Assessment of decentralization and local governance effectiveness",
        "The impact of corruption on democratic institutions",
        "Analysis of political party internal democracy",
        "The role of media in shaping political opinions",
        "Assessment of security sector reforms in Nigeria",
        "Analysis of inter-governmental relations in federal systems",
    ],
    "Mass Communication": [
        "Framing of farmer-herder conflicts in Nigerian newspapers",
        "Role of community radio in agricultural development in Nasarawa State",
        "Impact of social media influencers on the purchasing habits of NASU students",
        "Perception of fake news among rural dwellers in Nasarawa State",
        "Analysis of gender representation in Nigerian television adverts",
        "Use of public relations by NASU for its image management",
        "Audience perception of BBC Pidgin service in North-Central Nigeria",
        "Effectiveness of health communication campaigns on malaria prevention",
        "Comparative analysis of crisis reporting by online and traditional news platforms",
        "Film as a tool for cultural promotion: A study of Nollywood",
        # Additional topics
        "Digital journalism practices and challenges in Nigeria",
        "Analysis of media ownership and its impact on content diversity",
        "The role of citizen journalism in democratic societies",
        "Media framing of climate change issues in Nigeria",
        "Assessment of media literacy among secondary school students",
        "Impact of social media algorithms on news consumption patterns",
        "Analysis of political communication strategies during elections",
        "The role of media in conflict resolution and peacebuilding",
        "Assessment of investigative journalism practices in Nigeria",
        "Media representation of minority groups in Nigeria",
    ],
    "Economics": [
        "Impact of COVID-19 on small and medium enterprises (SMEs) in Lafia",
        "Effect of exchange rate volatility on import-dependent businesses in Nigeria",
        "Analysis of youth unemployment and its socioeconomic implications in Nasarawa State",
        "The relationship between government agricultural expenditure and food security",
        "Tax revenue and economic growth in Nigeria",
        "Poverty and income inequality in rural Nasarawa communities",
        "Impact of remittances from diaspora on household welfare",
        "Determinants of foreign direct investment (FDI) inflow into Nigeria",
        "Analysis of the effects of fuel subsidy removal on household consumption patterns",
        "The contribution of the solid minerals sector to Nasarawa State's GDP",
        # Additional topics
        "Analysis of informal sector contributions to economic development",
        "Impact of trade liberalization on domestic industries",
        "Assessment of monetary policy effectiveness in controlling inflation",
        "Analysis of household energy consumption patterns and expenditure",
        "Impact of infrastructure development on economic growth",
        "Assessment of microcredit programs on poverty alleviation",
        "Analysis of gender wage gaps in different economic sectors",
        "Impact of education quality on labor market outcomes",
        "Assessment of fiscal decentralization on regional development",
        "Analysis of sustainable development goals (SDGs) implementation",
    ],
    "Sociology": [
        "Drug abuse and its social consequences among youths in Karu LGA",
        "Socio-cultural factors influencing girl-child education in Toto LGA",
        "Impact of internal displacement due to conflict on family structures",
        "Social media and its influence on marital stability among young couples",
        "Traditional birth attendants and maternal healthcare in rural areas",
        "Perception and stigma associated with mental illness in Keffi",
        "The role of social networks in rural-urban migration decisions",
        "Child labor in artisanal mining sites in Nasarawa",
        "Changing patterns of marriage rites among the Eggon people",
        "Sociology of campus cultism: A case study of NASU",
        # Additional topics
        "Analysis of social capital and community development",
        "Impact of urbanization on traditional social structures",
        "Sociological analysis of religious movements and sects",
        "Gender roles and division of labor in contemporary families",
        "Social determinants of health disparities in rural communities",
        "Analysis of social mobility patterns in Nigerian society",
        "Impact of globalization on cultural identity and practices",
        "Sociological analysis of consumer culture and behavior",
        "Social factors influencing entrepreneurial success",
        "Analysis of social support systems for the elderly",
    ],
    "Psychology": [
        "Stress levels and coping strategies among final-year students of NASU",
        "Effect of social media addiction on academic performance",
        "Relationship between parenting styles and adolescent self-esteem",
        "Prevalence of depression among healthcare workers in public hospitals",
        "Impact of color on consumer buying behavior in supermarkets",
        "Psychological effects of prolonged unemployment on graduates",
        "Perception of domestic violence among married adults",
        "Correlation between personality traits and career choice among undergraduates",
        "Study habits and academic achievement in science and arts students",
        "Attitudes of students towards people with physical disabilities",
        # Additional topics
        "Psychological impact of social isolation during pandemics",
        "Assessment of cognitive biases in decision making",
        "Psychological factors influencing organizational commitment",
        "Impact of mindfulness practices on stress reduction",
        "Psychological assessment of learning disabilities in children",
        "Analysis of emotional intelligence and leadership effectiveness",
        "Psychological aspects of chronic illness management",
        "Impact of childhood trauma on adult psychological functioning",
        "Psychological factors in sports performance enhancement",
        "Assessment of psychological well-being in different age groups",
    ],
    
    # FACULTY OF ARTS
    "English Language": [
        "A stylistic analysis of selected political speeches",
        "Code-switching and code-mixing in Nigerian hip-hop music",
        "Feminist critique of selected works of a Nigerian female novelist",
        "Discourse analysis of gender representation in Nigerian textbooks",
        "Documentation of oral poetry of a minority ethnic group in Nasarawa",
        "Language of social media communication among Nigerian youths",
        "A contrastive analysis of English and Gwandara tense systems",
        "Pidgin English as a tool for national integration in Nigeria",
        "Study of neologisms in Nigerian English",
        "The theme of conflict in contemporary Nigerian drama",
        # Additional topics
        "Critical discourse analysis of media representations of migration",
        "Analysis of linguistic features in Nigerian blog writing",
        "Study of language attrition among Nigerian diaspora communities",
        "Pragmatic analysis of politeness strategies in Nigerian English",
        "Analysis of metaphor in political discourse",
        "Study of language variation in urban versus rural settings",
        "Critical analysis of postcolonial literature from Nigeria",
        "Study of language acquisition in multilingual environments",
        "Analysis of narrative techniques in contemporary Nigerian fiction",
        "Study of language and identity in immigrant communities",
    ],
    "History": [
        "History of the Alago people: Migration and settlement",
        "Impact of colonial rule on the traditional political system of the Eggon",
        "The role of Nasarawa State in Nigeria's civil war (1967-1970)",
        "Historical analysis of inter-group relations in the Middle Belt",
        "History of educational development in Nasarawa State (1996-date)",
        "Biographical study of a prominent traditional ruler in Nasarawa",
        "The evolution of Keffi from a pre-colonial town to a modern city",
        "Historical assessment of the mining industry in Nasarawa",
        "Nigeria's role in peacekeeping missions in Africa: A case study of Liberia",
        "The impact of Islam and Christianity on the culture of the Mada people",
        # Additional topics
        "Historical analysis of trade routes and economic exchange in pre-colonial Nigeria",
        "History of women's rights movements in Nigeria",
        "Historical assessment of environmental changes in Nasarawa State",
        "History of public health development in Nigeria",
        "Historical analysis of agricultural transformation in Nigeria",
        "History of transportation development in North-Central Nigeria",
        "Historical assessment of urbanization processes in Nigerian cities",
        "History of labor movements and trade unions in Nigeria",
        "Historical analysis of cultural festivals and their evolution",
        "History of technology adoption and diffusion in Nigeria",
    ],
    "Christian Religious Studies": [
        "Inter-religious dialogue as a tool for peacebuilding in conflict-prone communities",
        "The impact of Pentecostalism on moral values among youths in Karu",
        "Comparative analysis of burial rites in Islam and Christianity in Nasarawa",
        "The role of religious leaders in mitigating farmer-herder conflicts",
        "Trends in church growth and development in Keffi (2000-2023)",
        "The concept of peace in the Quran and the Bible",
        "Influence of African Traditional Religion on the practice of Christianity",
        "Religion and politics in Nigeria's Fourth Republic",
        "The phenomenon of religious pilgrimage: Economic and social impacts",
        "Biblical perspectives on environmental stewardship",
        # Additional topics
        "Theology of prosperity: A critical analysis of Nigerian Pentecostal churches",
        "Role of women in church leadership and ministry",
        "Comparative analysis of Christian and secular ethics in business",
        "Impact of Christianity on Nigerian art and culture",
        "Analysis of Christian responses to social justice issues",
        "The role of Christian education in moral formation",
        "Historical development of Christianity in Nasarawa State",
        "Analysis of contemporary worship practices in Nigerian churches",
        "Christian perspectives on marriage and family life",
        "The role of churches in community development projects",
    ],
    "Islamic Studies": [
        "The role of Islamic education in moral development of youth",
        "Comparative analysis of burial rites in Islam and Christianity",
        "The role of religious leaders in mitigating farmer-herder conflicts",
        "The concept of peace in Islamic teachings",
        "Doctrinal differences among major Islamic sects in Nasarawa State",
        "The impact of Islamic banking on financial inclusion in Nigeria",
        "Islamic perspectives on environmental conservation",
        "The contribution of Islamic scholars to the development of Nasarawa State",
        "Analysis of Zakat collection and distribution in Nasarawa State",
        "Islamic family law and its application in Nigerian courts",
        # Additional topics
        "The role of Sufism in Islamic spirituality in Nigeria",
        "Islamic perspectives on women's rights and gender equality",
        "Analysis of contemporary Islamic movements in Nigeria",
        "The impact of digital media on Islamic education",
        "Islamic ethics in business and commerce",
        "The role of mosques in community development",
        "Historical development of Islam in Nasarawa State",
        "Analysis of Islamic literature in Nigerian languages",
        "Islamic perspectives on conflict resolution and peacebuilding",
        "The role of Islamic NGOs in social welfare provision",
    ],
    "Arabic Studies": [
        "The influence of Arabic on the Hausa language in Nasarawa State",
        "Analysis of Arabic inscriptions in historical mosques of North-Central Nigeria",
        "Translation challenges of Arabic religious texts into Nigerian languages",
        "The role of Arabic in Islamic education in Nasarawa State",
        "Contribution of Arabic scholars to the intellectual history of Nasarawa",
        "Comparative study of Arabic dialects spoken in Nigerian Islamic schools",
        "Arabic literature and its influence on Nigerian Muslim writers",
        "The teaching of Arabic as a second language in Nigerian universities",
        "Arabic calligraphy as an art form in Nigerian mosques",
        "The impact of Arabic media on language learning in Nigeria",
        # Additional topics
        "Analysis of Arabic loanwords in Nigerian languages",
        "Arabic language maintenance among Nigerian diaspora communities",
        "Development of Arabic language teaching materials for Nigerian learners",
        "Analysis of Arabic poetry in Nigerian Islamic schools",
        "The role of Arabic in diplomatic relations with Arab countries",
        "Comparative analysis of Arabic and English grammar structures",
        "Arabic computational linguistics and natural language processing",
        "The impact of Arab culture on Nigerian Muslim communities",
        "Analysis of Arabic manuscripts in Nigerian libraries",
        "Arabic language policy and planning in Nigeria",
    ],
    "French": [
        "The role of French in Nigeria's foreign policy towards Francophone neighbors",
        "Challenges of teaching French as a foreign language in Nigerian secondary schools",
        "Translation issues in French-Nigerian diplomatic communications",
        "The influence of French culture on Nigerian fashion and cuisine",
        "Comparative analysis of educational systems in Nigeria and Francophone West Africa",
        "French language proficiency and employment opportunities in Nigeria",
        "The impact of Nigerian migrants in Francophone countries on cultural exchange",
        "Analysis of Nigerian literature translated into French",
        "The role of Alliance Française in promoting French language in Nigeria",
        "Code-switching patterns among French language learners in NASU",
        # Additional topics
        "Assessment of French language competence among Nigerian graduates",
        "Analysis of French media representation of Nigeria",
        "French for specific purposes: Business, tourism, diplomacy",
        "The impact of French language skills on career advancement",
        "Analysis of French loanwords in Nigerian English",
        "Development of digital resources for French language learning",
        "French language maintenance among Nigerian immigrants in Francophone countries",
        "Comparative analysis of French and English language teaching methodologies",
        "The role of French in regional integration in West Africa",
        "Analysis of French language attitudes among Nigerian students",
    ],
    "Theatre and Cultural Studies": [
        "Traditional festivals as a medium for cultural preservation in Nasarawa State",
        "The role of community theatre in development communication",
        "Analysis of Nollywood's representation of ethnic minorities",
        "Documentation and analysis of traditional dance forms of the Eggon people",
        "Theatre for development: A tool for health education in rural communities",
        "The impact of digital technology on Nigerian theatre production",
        "Costume and makeup design in traditional Nigerian performances",
        "The economics of cultural tourism in Nasarawa State",
        "Gender roles in traditional Nasarawa theatre",
        "Contemporary adaptations of Nigerian folktales for stage performance",
        # Additional topics
        "Analysis of contemporary Nigerian playwrights and their works",
        "The role of theatre in conflict resolution and peacebuilding",
        "Documentation of indigenous performance traditions",
        "Analysis of audience reception of different theatre genres",
        "The impact of globalization on Nigerian performing arts",
        "Development of community-based cultural festivals",
        "Analysis of theatre criticism in Nigerian media",
        "The role of arts administration in cultural development",
        "Analysis of children's theatre in Nigeria",
        "The impact of COVID-19 on performing arts industries",
    ],
    
    # FACULTY OF EDUCATION
    "Education and Biology": [
        "Effect of instructional materials on teaching and learning of biology",
        "Impact of laboratory practical sessions on students' understanding of biology",
        "Assessment of the biology curriculum and its relevance to local needs",
        "Comparative study of biology achievement in urban and rural schools",
        "Effect of concept mapping on students' performance in genetics",
        "Teachers' perception of the new biology curriculum content",
        "Relationship between students' attitude and performance in biology",
        "Effect of peer tutoring on academic achievement in biology",
        "Analysis of biology questions in WAEC examinations",
        "Integration of ICT in biology teaching and learning",
        # Additional topics
        "Effect of inquiry-based learning on students' conceptual understanding",
        "Assessment of field trip effectiveness in biology education",
        "Development of locally relevant biology teaching materials",
        "Analysis of common misconceptions in biology concepts",
        "Effect of cooperative learning strategies on biology achievement",
        "Assessment of biology laboratory safety practices",
        "Development of assessment rubrics for biology practicals",
        "Effect of differentiated instruction on diverse learners",
        "Analysis of biology textbook content for cultural relevance",
        "Assessment of biology teachers' professional development needs",
    ],
    "Education and Chemistry": [
        "Effect of demonstration method on students' performance in chemistry",
        "Assessment of laboratory facilities for chemistry teaching in secondary schools",
        "Students' misconceptions in balancing chemical equations",
        "Effect of computer simulation on teaching chemical bonding",
        "Relationship between mathematical ability and chemistry performance",
        "Analysis of difficult topics in chemistry according to students and teachers",
        "Effect of practical work on students' interest in chemistry",
        "Gender differences in chemistry achievement in Nasarawa State",
        "Evaluation of chemistry textbooks used in secondary schools",
        "Strategies for improving performance in chemistry practical examinations",
        # Additional topics
        "Effect of problem-based learning on chemistry understanding",
        "Assessment of chemistry teachers' content knowledge",
        "Development of low-cost chemistry laboratory equipment",
        "Analysis of safety awareness in chemistry laboratories",
        "Effect of multimedia resources on chemistry learning",
        "Assessment of chemistry curriculum implementation challenges",
        "Development of context-based chemistry teaching modules",
        "Effect of formative assessment on chemistry achievement",
        "Analysis of students' anxiety towards chemistry",
        "Assessment of outdoor chemistry learning activities",
    ],
    "Education and Mathematics": [
        "Effect of gender on students' academic achievement in mathematics",
        "Impact of instructional materials on teaching and learning of mathematics",
        "Assessment of factors affecting students' performance in mathematics",
        "Effect of class size on effective teaching and learning of mathematics",
        "Students' perception towards the study of mathematics",
        "Comparative analysis of mathematics achievement using different teaching methods",
        "The role of parental involvement in students' mathematics performance",
        "Assessment of mathematics anxiety among secondary school students",
        "Effect of problem-based learning on students' interest in mathematics",
        "Analysis of common errors in solving algebraic equations",
        # Additional topics
        "Effect of manipulatives on understanding mathematical concepts",
        "Assessment of mathematics teachers' pedagogical content knowledge",
        "Development of mathematics games for enhanced learning",
        "Analysis of mathematical reasoning skills among students",
        "Effect of peer assessment on mathematics learning",
        "Assessment of technology integration in mathematics teaching",
        "Development of culturally relevant mathematics problems",
        "Effect of metacognitive strategies on mathematics problem-solving",
        "Analysis of mathematics curriculum alignment with assessment",
        "Assessment of mathematics intervention programs effectiveness",
    ],
    "Education and Physics": [
        "Perception of students towards the study of physics",
        "Effect of practical activities on students' understanding of physics concepts",
        "Assessment of physics laboratory equipment in secondary schools",
        "Students' difficulties in understanding electromagnetic concepts",
        "Effect of computer-assisted instruction on physics achievement",
        "Gender differences in physics performance and interest",
        "Analysis of physics questions in national examinations",
        "Strategies for improving enrollment in physics classes",
        "The relationship between physics knowledge and career choice",
        "Integration of real-world applications in physics teaching",
        # Additional topics
        "Effect of demonstration experiments on physics learning",
        "Assessment of physics teachers' content knowledge gaps",
        "Development of low-cost physics teaching aids",
        "Analysis of students' conceptual difficulties in mechanics",
        "Effect of collaborative learning on physics understanding",
        "Assessment of physics laboratory work effectiveness",
        "Development of context-based physics teaching materials",
        "Effect of analogies on understanding abstract physics concepts",
        "Analysis of physics curriculum relevance to everyday life",
        "Assessment of physics education research impact on teaching",
    ],
    "Education and English Language": [
        "Challenges facing the teaching of English language in rural primary schools",
        "Effect of mother tongue interference on English pronunciation",
        "Assessment of reading comprehension skills among secondary school students",
        "Strategies for improving essay writing skills",
        "The role of language laboratory in English language teaching",
        "Students' attitude towards English language learning",
        "Error analysis in students' written composition",
        "Effect of drama activities on English language proficiency",
        "Assessment of English language textbooks for appropriateness",
        "The impact of social media on students' English writing skills",
        # Additional topics
        "Effect of extensive reading on vocabulary development",
        "Assessment of listening comprehension skills among learners",
        "Development of speaking skills through communicative activities",
        "Analysis of grammar teaching methods effectiveness",
        "Effect of peer feedback on writing improvement",
        "Assessment of English language teachers' proficiency levels",
        "Development of multimedia resources for English teaching",
        "Effect of literature-based approach on language learning",
        "Analysis of English language assessment practices",
        "Assessment of English for specific purposes programs",
    ],
    "Education and Economics": [
        "Effect of class size on effective teaching and learning of economics",
        "Assessment of factors affecting students' performance in economics",
        "Students' perception towards the study of economics",
        "Impact of teaching aids on students' achievement in economics",
        "Comparative study of economics achievement in public and private schools",
        "The relationship between economic literacy and financial behavior of students",
        "Analysis of economics curriculum for relevance to current economic realities",
        "Effect of field trips on students' understanding of economic concepts",
        "Assessment of economics practical projects in secondary schools",
        "Gender differences in economics performance in NASU",
        # Additional topics
        "Effect of case study method on economics understanding",
        "Assessment of economics teachers' pedagogical approaches",
        "Development of local case studies for economics teaching",
        "Analysis of students' misconceptions in economics",
        "Effect of simulation games on economics learning",
        "Assessment of economics curriculum implementation challenges",
        "Development of economics teaching resources from local data",
        "Effect of current affairs integration on economics interest",
        "Analysis of economics examination question patterns",
        "Assessment of economics education for sustainable development",
    ],
    "Education and Geography": [
        "Effect of field trips on students' understanding of geography concepts",
        "Assessment of geography teaching resources in secondary schools",
        "Students' difficulties in map reading and interpretation",
        "Impact of GIS technology on geography education",
        "The role of geography education in environmental awareness",
        "Comparative analysis of geography curricula in Nigeria and other countries",
        "Effect of climate change education on students' environmental behavior",
        "Assessment of geography examination questions for cognitive levels",
        "Strategies for improving interest in physical geography topics",
        "Integration of local examples in geography teaching",
        # Additional topics
        "Effect of project-based learning on geography skills",
        "Assessment of geography teachers' technological competence",
        "Development of local case studies for geography teaching",
        "Analysis of students' spatial thinking abilities",
        "Effect of outdoor learning on geography understanding",
        "Assessment of geography curriculum relevance to local issues",
        "Development of geography teaching aids from local materials",
        "Effect of collaborative mapping activities on learning",
        "Analysis of geography fieldwork implementation challenges",
        "Assessment of geography education for sustainable development",
    ],
    "Education and History": [
        "Challenges of teaching history in Nigerian secondary schools",
        "Students' perception of history as a subject of study",
        "The use of primary sources in history teaching",
        "Assessment of history textbooks for accuracy and balance",
        "Effect of storytelling method on students' interest in history",
        "The role of history education in national identity formation",
        "Integration of local history in the secondary school curriculum",
        "Students' understanding of historical thinking skills",
        "The impact of digital resources on history teaching and learning",
        "Assessment of history questions in WAEC for cognitive demand",
        # Additional topics
        "Effect of historical site visits on history learning",
        "Assessment of history teachers' content knowledge",
        "Development of oral history projects for student engagement",
        "Analysis of students' historical empathy development",
        "Effect of role-playing activities on historical understanding",
        "Assessment of history curriculum implementation issues",
        "Development of local history teaching materials",
        "Effect of documentary films on history interest",
        "Analysis of historical thinking skills assessment methods",
        "Assessment of history education for citizenship development",
    ],
    "Education and Christian Religious Studies": [
        "Effect of values education on moral behavior of students",
        "Assessment of Christian Religious Studies curriculum content",
        "Students' perception of Christian Religious Studies as a subject",
        "The role of religious education in character development",
        "Comparative study of religious education in public and faith-based schools",
        "Challenges of teaching religious pluralism in CRS classes",
        "Integration of community service in Christian Religious Studies",
        "Assessment of CRS textbooks for doctrinal accuracy and inclusivity",
        "The impact of religious instruction on students' social behavior",
        "Strategies for making CRS relevant to contemporary issues",
        # Additional topics
        "Effect of parables and stories on moral understanding",
        "Assessment of CRS teachers' theological training adequacy",
        "Development of interfaith dialogue activities in CRS",
        "Analysis of students' moral reasoning development",
        "Effect of service-learning projects on character formation",
        "Assessment of CRS curriculum relevance to youth issues",
        "Development of multimedia resources for CRS teaching",
        "Effect of role models and biographies on values education",
        "Analysis of assessment methods in CRS",
        "Assessment of CRS contribution to peace education",
    ],
    "Education and Islamic Studies": [
        "Assessment of Islamic Studies curriculum in Nigerian secondary schools",
        "Students' perception of Islamic Studies as a subject of study",
        "The role of Islamic education in moral development",
        "Challenges of teaching Islamic Studies in multi-religious settings",
        "Integration of contemporary issues in Islamic Studies curriculum",
        "Effect of memorization techniques on Quranic recitation skills",
        "Assessment of Arabic language competency among Islamic Studies students",
        "The role of Islamic schools in educational development",
        "Comparative study of Islamic education in Nigeria and other countries",
        "Strategies for improving interest in Islamic Studies",
        # Additional topics
        "Effect of storytelling from Islamic history on learning",
        "Assessment of Islamic Studies teachers' pedagogical approaches",
        "Development of digital resources for Islamic Studies",
        "Analysis of students' understanding of Islamic ethics",
        "Effect of project-based learning on Islamic Studies",
        "Assessment of Islamic Studies curriculum implementation",
        "Development of Islamic finance education modules",
        "Effect of mosque-based learning activities",
        "Analysis of assessment practices in Islamic Studies",
        "Assessment of Islamic Studies contribution to moral education",
    ],
    "Education and French": [
        "Challenges of teaching French in Nigerian secondary schools",
        "Students' attitude towards learning French as a foreign language",
        "Assessment of French language teaching resources",
        "Effect of immersion programs on French language proficiency",
        "The role of French language in career opportunities for Nigerian graduates",
        "Comparative analysis of French teaching methods",
        "Integration of technology in French language teaching",
        "Assessment of French language examinations for communicative competence",
        "Strategies for improving French pronunciation among Nigerian learners",
        "The impact of cultural awareness on French language learning",
        # Additional topics
        "Effect of language exchange programs on French proficiency",
        "Assessment of French teachers' linguistic competence",
        "Development of contextualized French teaching materials",
        "Analysis of students' speaking anxiety in French classes",
        "Effect of authentic materials on French learning",
        "Assessment of French curriculum implementation challenges",
        "Development of French for specific purposes courses",
        "Effect of drama activities on French language skills",
        "Analysis of assessment methods in French language teaching",
        "Assessment of French education policy implementation",
    ],
    "Education and Integrated Science": [
        "Assessment of integrated science curriculum for interdisciplinary connections",
        "Effect of practical activities on integrated science achievement",
        "Students' perception of integrated science as a foundational subject",
        "Challenges of teaching integrated science in rural primary schools",
        "The role of integrated science in preparing students for senior science subjects",
        "Assessment of integrated science textbooks for accuracy and appropriateness",
        "Effect of inquiry-based learning on integrated science performance",
        "Integration of environmental education in integrated science teaching",
        "Gender differences in interest and performance in integrated science",
        "Strategies for improving practical skills in integrated science",
        # Additional topics
        "Effect of hands-on experiments on science process skills",
        "Assessment of integrated science teachers' content knowledge",
        "Development of low-cost science teaching materials",
        "Analysis of students' science misconceptions",
        "Effect of outdoor science activities on learning",
        "Assessment of laboratory safety practices in integrated science",
        "Development of local context science teaching examples",
        "Effect of collaborative learning in integrated science",
        "Analysis of integrated science assessment practices",
        "Assessment of science education for sustainable development",
    ],
    
    # FACULTY OF ADMINISTRATION
    "Accounting": [
        "Impact of computerized accounting on financial reporting accuracy",
        "Analysis of internal control systems in public sector organizations",
        "Effect of forensic accounting on fraud detection in Nigerian banks",
        "Assessment of accounting students' readiness for professional practice",
        "The role of management accounting in decision making of SMEs",
        "Impact of IFRS adoption on financial statements of Nigerian companies",
        "Tax compliance behavior of small businesses in Nasarawa State",
        "Effect of corporate governance on financial performance of listed companies",
        "Analysis of cost accounting practices in manufacturing firms",
        "The role of budgeting in financial management of local governments",
        # Additional topics
        "Impact of digital transformation on accounting practices",
        "Assessment of audit quality determinants in Nigeria",
        "Analysis of corporate social responsibility reporting practices",
        "Effect of taxation policies on investment decisions",
        "Assessment of accounting information systems effectiveness",
        "Analysis of earnings management practices in Nigerian firms",
        "Impact of blockchain technology on accounting processes",
        "Assessment of sustainability accounting implementation",
        "Analysis of accounting ethics and professional conduct",
        "Impact of accounting standards convergence on financial reporting",
    ],
    "Business Administration": [
        "Impact of entrepreneurship education on business startup intentions",
        "Effect of leadership styles on employee performance in banking sector",
        "Analysis of customer relationship management practices in Nigerian businesses",
        "Strategic planning and organizational performance in SMEs",
        "The role of e-commerce in business growth in Nasarawa State",
        "Impact of COVID-19 on business operations and survival strategies",
        "Human resource management practices in Nigerian public organizations",
        "Effect of organizational culture on employee productivity",
        "Marketing strategies for promoting local agricultural products",
        "Supply chain management challenges in Nigerian manufacturing firms",
        # Additional topics
        "Impact of digital marketing on consumer behavior",
        "Assessment of change management practices in organizations",
        "Analysis of innovation management in Nigerian companies",
        "Effect of corporate social responsibility on brand image",
        "Assessment of talent management strategies effectiveness",
        "Analysis of business process reengineering implementation",
        "Impact of artificial intelligence on business operations",
        "Assessment of risk management practices in businesses",
        "Analysis of strategic alliances and partnerships",
        "Impact of business intelligence on decision making",
    ],
    "Public Administration": [
        "Assessment of e-governance implementation in Nasarawa State",
        "The effectiveness of local government administration in rural development",
        "Impact of civil service reforms on public sector performance",
        "Analysis of public policy implementation challenges in Nigeria",
        "The role of traditional institutions in local governance",
        "Assessment of performance management systems in public organizations",
        "Impact of political interference on civil service efficiency",
        "Analysis of bureaucratic bottlenecks in license and permit processing",
        "The role of public-private partnerships in infrastructure development",
        "Assessment of transparency and accountability in public financial management",
        # Additional topics
        "Impact of digital government services on citizen satisfaction",
        "Assessment of public sector leadership development programs",
        "Analysis of public service motivation among civil servants",
        "Effect of decentralization on service delivery efficiency",
        "Assessment of anti-corruption measures effectiveness",
        "Analysis of public sector innovation adoption",
        "Impact of citizen participation in governance processes",
        "Assessment of public sector human resource development",
        "Analysis of inter-governmental relations effectiveness",
        "Impact of administrative reforms on organizational performance",
    ],
    "Banking and Finance": [
        "Impact of mobile banking on financial inclusion in rural areas",
        "Analysis of credit risk management practices in Nigerian banks",
        "Effect of interest rate policies on bank lending behavior",
        "Assessment of microfinance institutions in poverty alleviation",
        "The role of financial technology (FinTech) in banking sector transformation",
        "Impact of bank consolidation on competitive performance",
        "Analysis of foreign exchange management in Nigerian banks",
        "Effect of corporate governance on bank performance",
        "Assessment of agricultural financing by commercial banks",
        "The role of development finance institutions in economic development",
        # Additional topics
        "Impact of digital currencies on traditional banking",
        "Assessment of liquidity risk management in banks",
        "Analysis of investment portfolio management strategies",
        "Effect of regulatory compliance on bank operations",
        "Assessment of financial inclusion strategies effectiveness",
        "Analysis of merger and acquisition impacts in banking",
        "Impact of artificial intelligence on financial services",
        "Assessment of Islamic banking growth and challenges",
        "Analysis of capital market development in Nigeria",
        "Impact of financial literacy programs on economic empowerment",
    ],
    "Entrepreneurship Studies": [
        "Factors influencing entrepreneurial intentions among university students",
        "Assessment of government support programs for young entrepreneurs",
        "The role of business incubators in startup success",
        "Challenges facing women entrepreneurs in Nasarawa State",
        "Impact of entrepreneurship education on self-employment decisions",
        "Analysis of innovation practices among small business owners",
        "The role of social capital in entrepreneurial success",
        "Assessment of funding sources for new business ventures",
        "Entrepreneurial opportunities in agricultural value chains",
        "Impact of mentorship on entrepreneurial business growth",
        # Additional topics
        "Analysis of digital entrepreneurship opportunities",
        "Assessment of entrepreneurial ecosystem development",
        "Effect of cultural factors on entrepreneurial behavior",
        "Assessment of green entrepreneurship initiatives",
        "Analysis of family business succession planning",
        "Impact of entrepreneurial networks on venture growth",
        "Assessment of social entrepreneurship models",
        "Analysis of entrepreneurial failure and learning",
        "Effect of regulatory environment on entrepreneurship",
        "Assessment of youth entrepreneurship programs effectiveness",
    ],
    
    # FACULTY OF LAW
    "Law": [
        "Analysis of land rights and tenure security in Nasarawa State",
        "The legal framework for environmental protection in Nigeria",
        "Assessment of alternative dispute resolution mechanisms for farmer-herder conflicts",
        "Human rights implications of internally displaced persons in Nigeria",
        "Legal challenges of e-commerce in Nigeria",
        "Analysis of intellectual property protection for traditional knowledge",
        "The effectiveness of anti-corruption legislation in Nigeria",
        "Legal aspects of corporate governance in Nigerian companies",
        "Assessment of consumer protection laws and their enforcement",
        "The legal framework for public-private partnerships in Nigeria",
        # Additional topics
        "Analysis of cybercrime legislation and enforcement challenges",
        "Assessment of judicial independence in Nigeria",
        "Legal framework for climate change adaptation and mitigation",
        "Analysis of labor law and workers' rights protection",
        "Assessment of constitutional amendments and their impacts",
        "Legal aspects of artificial intelligence and automation",
        "Analysis of international humanitarian law application",
        "Assessment of legal education reform needs",
        "Legal framework for renewable energy development",
        "Analysis of privacy and data protection laws",
    ],
    
    # FACULTY OF ENVIRONMENTAL SCIENCE
    "Environmental Management": [
        "Assessment of solid waste management practices in Keffi",
        "Environmental impact assessment of mining activities in Nasarawa State",
        "Analysis of air quality in urban areas of Lafia",
        "Water resource management and sustainable development",
        "Assessment of deforestation and its impact on local climate",
        "Climate change adaptation strategies among farmers",
        "Environmental awareness and behavior among university students",
        "Assessment of pollution levels in major rivers of Nasarawa State",
        "The role of environmental NGOs in conservation efforts",
        "Sustainable solid waste management through recycling initiatives",
        # Additional topics
        "Assessment of environmental justice issues in local communities",
        "Analysis of ecosystem services valuation methods",
        "Impact of urbanization on environmental quality",
        "Assessment of environmental policy implementation effectiveness",
        "Analysis of circular economy opportunities",
        "Impact of industrial activities on environmental health",
        "Assessment of renewable energy adoption barriers",
        "Analysis of environmental risk assessment methodologies",
        "Impact of agricultural practices on water quality",
        "Assessment of corporate environmental responsibility practices",
    ],
    "Architecture": [
        "Sustainable building design for hot climatic conditions in Nasarawa",
        "Traditional architecture and its adaptation to modern needs",
        "Assessment of housing quality in low-income urban settlements",
        "Energy-efficient design strategies for public buildings",
        "The role of green spaces in urban planning of Keffi",
        "Adaptive reuse of historical buildings for contemporary functions",
        "Assessment of accessibility features in public buildings",
        "Sustainable materials for affordable housing construction",
        "Analysis of urban sprawl and its impact on architectural planning",
        "Bioclimatic design principles for educational buildings",
        # Additional topics
        "Analysis of vernacular architecture principles for contemporary design",
        "Assessment of building information modeling (BIM) adoption",
        "Design for disaster-resilient buildings in flood-prone areas",
        "Analysis of indoor environmental quality in office buildings",
        "Assessment of sustainable campus design principles",
        "Analysis of participatory design approaches in community projects",
        "Assessment of architectural heritage conservation methods",
        "Analysis of modular construction techniques for housing",
        "Assessment of smart building technologies integration",
        "Analysis of architectural design for healthcare facilities",
    ],
    "Geography": [
        "Land use and land cover change analysis using remote sensing",
        "Assessment of urban growth patterns in Lafia",
        "Geographic information systems for infrastructure planning",
        "Climate variability and its impact on agricultural production",
        "Analysis of settlement patterns in rural Nasarawa",
        "Geographic analysis of healthcare facility distribution",
        "Assessment of flood-prone areas using GIS techniques",
        "Transportation network analysis for improved accessibility",
        "Soil mapping for agricultural zonation",
        "Population distribution and migration patterns in Nasarawa State",
        # Additional topics
        "Analysis of watershed management approaches",
        "Assessment of food security and vulnerability mapping",
        "Analysis of coastal zone management challenges",
        "Assessment of renewable energy resource mapping",
        "Analysis of disease spatial patterns and determinants",
        "Assessment of tourism potential and infrastructure mapping",
        "Analysis of urban heat island effects",
        "Assessment of land degradation and restoration options",
        "Analysis of water resource conflict mapping",
        "Assessment of climate change vulnerability indices",
    ],
    "Urban and Regional Planning": [
        "Assessment of informal settlements and upgrading strategies",
        "Transportation planning for sustainable urban mobility",
        "Land use planning for balanced urban development",
        "Assessment of recreational facilities in urban areas",
        "Housing policy analysis and affordable housing provision",
        "Urban renewal strategies for declining city centers",
        "Regional development planning for balanced growth",
        "Assessment of urban infrastructure and service delivery",
        "Community participation in urban planning processes",
        "Smart city concepts and their applicability in Nigerian cities",
        # Additional topics
        "Analysis of transit-oriented development opportunities",
        "Assessment of urban resilience planning frameworks",
        "Analysis of mixed-use development impacts",
        "Assessment of urban agriculture integration in city planning",
        "Analysis of gentrification processes and impacts",
        "Assessment of inclusive city planning approaches",
        "Analysis of urban governance structures effectiveness",
        "Assessment of disaster risk reduction in urban planning",
        "Analysis of peri-urban development challenges",
        "Assessment of sustainable urban drainage systems",
    ],
    
    # FACULTY OF MEDICAL AND HEALTH SCIENCES
    "Nursing": [
        "Assessment of nursing care quality in public hospitals",
        "Factors affecting job satisfaction among nurses in Nasarawa State",
        "Knowledge and practice of infection control among nursing students",
        "Assessment of maternal healthcare services in primary health centers",
        "The role of nurses in health education and disease prevention",
        "Challenges facing nursing practice in rural health facilities",
        "Assessment of patient satisfaction with nursing care",
        "Knowledge and attitude of nurses towards palliative care",
        "The impact of nurse staffing levels on patient outcomes",
        "Assessment of nursing documentation practices in hospitals",
        # Additional topics
        "Analysis of nursing leadership and management practices",
        "Assessment of evidence-based nursing practice implementation",
        "Analysis of nursing education curriculum relevance",
        "Assessment of nurse-patient communication effectiveness",
        "Analysis of nursing workforce migration patterns",
        "Assessment of nursing research utilization in practice",
        "Analysis of cultural competence in nursing care",
        "Assessment of nursing informatics skills and training needs",
        "Analysis of ethical challenges in nursing practice",
        "Assessment of continuing professional development for nurses",
    ],
}

# Default topics for departments not specifically listed
DEFAULT_TOPICS = [
    "Analysis of current trends and challenges in your field of study",
    "Impact of technology adoption on practices in your discipline",
    "Assessment of professional development needs in your field",
    "Comparative study of local and international best practices",
    "The role of education and training in improving sector outcomes",
    "Sustainability considerations in your discipline",
    "Policy analysis and recommendations for your field",
    "Case study analysis of successful projects in your area",
    "Stakeholder perspectives on key issues in your discipline",
    "Future trends and predictions for your field of study",
    # Additional default topics
    "Analysis of ethical issues and dilemmas in professional practice",
    "Assessment of quality assurance mechanisms in service delivery",
    "Analysis of interdisciplinary collaboration opportunities",
    "Assessment of regulatory frameworks and compliance requirements",
    "Analysis of innovation adoption barriers and facilitators",
    "Assessment of community engagement and outreach strategies",
    "Analysis of knowledge management practices",
    "Assessment of performance measurement and evaluation systems",
    "Analysis of organizational learning and development",
    "Assessment of strategic planning and implementation",
]