# Generated by Django 6.0 on 2026-01-08 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaterial',
            name='file_format',
            field=models.CharField(blank=True, help_text='File format (e.g. PDF, DOCX)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectmaterial',
            name='page_count',
            field=models.IntegerField(blank=True, help_text='Number of pages in the document', null=True),
        ),
        migrations.AlterField(
            model_name='projectmaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
