# Generated by Django 6.0 on 2026-01-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmaterial_file_format_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
